#! /bin/bash

CONTAINER_NAME=elixir_livebook

if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
    echo "Container $CONTAINER_NAME found"
    if [ ! "$(docker ps -aq -f status=exited -f name=$CONTAINER_NAME)" ]; then
        echo "Stopping $CONTAINER_NAME"
        docker stop $CONTAINER_NAME
    fi
    echo "Removing $CONTAINER_NAME"
    docker rm $CONTAINER_NAME
fi
